name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build-metrics:
    runs-on: ubuntu-latest
    environment:
      name: Metrics
    permissions:
      contents: write
    steps:
      - name: Generate GitHub profile metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Pablo-Manglano-Redondo
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          filename: github-metrics.svg
          output_action: commit
          committer_message: "chore: update metrics"
