name: Generate Full-year Calendar

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta el workflow a medianoche todos los días
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Generate Full-year Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
