name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # todos los días a las 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub profile metrics
        uses: lowlighter/metrics@latest
        with:
          # --- Auth ---
          # PAT guardado en Settings > Secrets > Actions > METRICS_TOKEN
          # Recomendado: scopes mínimos -> repo:read, read:user
          token: ${{ secrets.METRICS_TOKEN }}

          # --- Target ---
          user: Pablo-Manglano-Redondo
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid

          # --- Achievements (logros bonitos tipo "maintainer", "developer", etc) ---
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_achievements_secrets: no

          # --- Habits (tus hábitos de contribución) ---
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 100
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          # --- Isocalendar (calendario de contribuciones semanal/año) ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # --- Lines of code changed (pequeño vanity metric de actividad reciente de código) ---
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          # --- Output ---
          filename: github-metrics.svg
          output_action: commit
          committer_message: "chore: update metrics"
